version: '2'
services:
  database:
    image: mysql:5.6
    command: ['--default-authentication-plugin=mysql_native_password', '--default-time-zone=-07:00']
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reports_bd
      MYSQL_USER: UAS_user
      MYSQL_PASSWORD: UAS_password