//Port
export const SERVER_PORT = 'PORT';

//JWT
export const JWT_SECRET = 'JWT_SECRET';

//Database
export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABASE_USERNAME = 'DATABASE_USERNAME';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_NAME = 'DATABASE_NAME';

//Default user
export const DEFAULT_USER_NAME = 'DEFAULT_USER_NAME';
export const DEFAULT_USER_LAST_NAME = 'DEFAULT_USER_LAST_NAME';
export const DEFAULT_USER = 'DEFAULT_USER';
export const DEFAULT_USER_PASSWORD = 'DEFAULT_USER_PASSWORD';
export const DEFAULT_USER_ROL = 'DEFAULT_USER_ROL';
